name: ice_cream_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  stylish_bottom_bar: ^1.0.1
  provider: ^6.0.4
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.3.3
  http: ^1.2.0
  lottie: ^2.0.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/image8.png"
